name: bbt
channels: 
  - conda-forge
  - bioconda
dependencies:
  - graphviz=7.0.6
  - loguru=0.6.0
  - mamba=1.2.0 
  - matplotlib=3.6.3
  - numpy=1.24.1
  - pandas=1.5.2
  - scipy=1.9.3
  - snakemake=7.20.0
