name: bbt
channels: 
  - conda-forge
  - bioconda
dependencies:
  - dtaidistance=2.3.10 
  - fastdtw=0.3.4
  - graphviz=7.0.6
  - loguru=0.6.0
  - mamba=1.2.0 
  - matplotlib=3.6.3 
  - numpy=1.24.1
  - openpyxl=3.0.10  
  - pandas=1.5.2
  - pip
  - scipy=1.9.3
  - seaborn=0.12.2 
  - snakemake=7.20.0
  - pip:
    - fastparquet=2023.8.0
    - multiprocess=0.70.15 
    - scikit-learn=1.3.0
    - pyarrow=13.0.0
    - ruptures=1.1.9
